// Barrel exports pour les composants admin
export { AdminSidebar } from './admin-sidebar'
export { AdminSidebarWrapper } from './admin-sidebar-wrapper'
export { AdminSidebarProvider } from './admin-sidebar-provider'
export { AdminLogo } from './admin-logo'
export { AdminUserMenu } from './admin-user-menu'
export { AdminQuickActions } from './admin-quick-actions'
export { UserCreateForm } from './user-create-form'
export { UserCreateModal } from './user-create-modal'
export { UserEditForm } from './user-edit-form'
export { UserEditModal } from './user-edit-modal'
export { UserDetailsModal } from './user-details-modal'
export { UserDetailsModal as UserViewModal } from './user-view-modal'
export { UserQuickActions } from './user-quick-actions'
export { AdminModal as Modal } from './modal'
export { AdminModalWithHeader as ModalWithHeader } from './modal-with-header'
export { SystemSettingsForm } from './system-settings-form'
export { SettingsActions } from './settings-actions'
export { SystemInfoCard } from './system-info-card'
export { ActivityLogsTable } from './activity-logs-table'
export { ActivityLogsFilters } from './activity-logs-filters'
export { ActivityLogsExportButton } from './activity-logs-export-button'
export { ActivityLogsTableSkeleton as ActivityLogsSkeleton } from './activity-logs-skeleton'
export { LogRow as ActivityLogRow } from './activity-log-row'
export { ActivityBadge as ActivityLogBadge } from './activity-log-badge'
export { ResourceIcon as ActivityLogResourceIcon } from './activity-log-resource-icon'
export { ActivityStatsCards } from './activity-stats-cards'
export { OnboardingForm } from './onboarding-form'
export { EnhancedOnboardingForm } from './enhanced-onboarding-form'
export { OnboardingSuccess } from './onboarding-success' 